# **DATASET RANDOMICO**:


In [ ]:
# importação de modulos
import pandas as pd
import numpy as np

# Criando DataFrame com valores aleatorios
df = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
df

b         d         e
Utah   -0.850818  0.944331  0.465236
Ohio   -0.163839  0.160571  0.983403
Texas  -1.189216 -1.620468  0.117296
Oregon  0.113578  0.841267 -1.276912

# **Map()**;

## Descrição:

A função map é destinada para realizar transformações de dados de uma lista ou Series.

### Vantagens:
A função map aplica o principio de vetorização em lista ou Series aumentando assim a performance.

### Desvatagens:
Como dito anteriormente o objetivo do map é apenas para transformação de dados. Sendo assim não é possivel implementar uma estruturas de decisão nessa função





In [ ]:
df.b.map(lambda x: x + 1)

In [ ]:
# Criando função lambda para testes
format = lambda x: x + 1

df.b.map(format)

# **Apply()**;

## Descrição:
a função apply assim como seu nome da a entender aplica uma função a uma lista ou Series de dados.

### Vantagens:
Ao contrario do map, com o apply é possivel aplicar uma função para transformação de dados com estruturas de decisão.

### Desvatagens:
A função aplly não aplica vetorização assim como map, ou seja aplly não tem um performance tão boa assim como map


In [ ]:
df.b.apply(lambda x: x + 1)

In [ ]:
df.b.apply(format) # isso tambem funciona

In [ ]:
# utilizando o apply com varias colunas como parametro e armazenando saida em outra coluna

def func_exemplo(field):
    ...

Acertos_Acum = 'dataframe exemplo'


Acertos_Acum['tipo_Acerto'] = Acertos_Acum.apply(lambda x: func_exemplo(x['Cd_Ocorrencia']), axis=1)

In [ ]:

def split_parcel(valor_total):
    parcela = round((valor_total / 5), 2)
    total_parcela = parcela * 5
    diferenca = round((valor_total - total_parcela), 2)
    parcela_5 = round((parcela + diferenca), 2)
    return pd.Series([parcela, parcela_5])

def resolve_data(base_path):
    df_path = Path.joinpath(base_path, Path('database\\ipva.xls'))
    df = pd.read_excel(df_path)df
    print(df.dtypes)
    df[['PACELA_1-4', 'PACELA_5']] = df.apply(lambda x: split_parcel(x['IPVA']), axis=1)

# **ApplyMap**();

## Descrição:
A função apllymap é uma junção conceitos do apply e map, sendo que o mesmo aplica a função map em uma ou mais Series.

### Vantagens:
Com applymap é possivel aplicar um map em varias Series ou em todo um DataFrame de forma vetorizada.**negrito**

In [ ]:
def label(element):
    if element > 0.5:
        return 'High'
    else:
        return 'Low'


def uppStr(ss):
  return ss.upper()

df[['b','e',]].applymap(label)

df[['b','e',]].applymap(label).applymap(lambda x: x.upper())
df[['b','e',]].applymap(label).applymap(uppStr)


# df[['A', 'B', 'C']].applymap(str.strip)
# df[['A', 'B', 'C']].applymap(str)

b     e
Utah     LOW   LOW
Ohio    HIGH   LOW
Texas    LOW  HIGH
Oregon   LOW   LOW

# **Pandas Unique**

## Descrição:
Retorna valores unicos de uma serie com base em uma conversão de valores em Hash

In [ ]:
frame1 = pd.Series([2, 1, 3, 3])
frame2 = pd.Series([2, 2, 1, 2])
frame3 = pd.Series([1, 2, 3, 4])

In [ ]:
full_frame = pd.concat([frame1, frame2, frame3], axis=1)

0  1  2
0  2  2  1
1  1  2  2
2  3  1  3
3  3  2  4

In [ ]:
# Duas maneiras de fazer a mesma coisa

pd.unique(frame1)

frame1.unique()

array([2, 1, 3])

In [ ]:
full_frame[1].unique()
full_frame.iloc[1].unique()

array([1, 2])

---
# **Pandas NaN**
- df.isna()
- df.dropna()
- df.fillna()

---
# **Numpy NaN**
- np.NaN()
- np.inf()
---

# **pandas.DataFrame.isna**

Retorna um objeto booleano de mesmo tamanho indicando se os valores são NA. Valores NA, como Nenhum ou `numpy.NaN`, são mapeados para valores True. Todo o resto é mapeado para valores False. Caracteres como strings vazias '' ou `numpy.inf` não são considerados valores NA (a menos que você defina )`.pandas.options.mode.use_inf_as_na = True`

# **pandas.DataFrame.dropna**
Remova os valores ausentes (NaN)

# **pandas.DataFrame.fillna**
O fillna()método substitui os valores NULL por um valor especificado.

# **numpy.inf (numeric infinity)**
atribui um valor simbolico ao numero que é ou pode ser infinito

# **numpy.nan (Not a Number)**
atribui um valor simbolico ao valor que não corresponde a nenhum tipo basico



In [ ]:
df=pd.DataFrame({"A":[5,3,np.nan,4],
                 "B":[np.inf,2,4,3],
                 "C":[4,3,8,5],
                 "D":[5,4,2,None]})

df

A    B  C    D
0  5.0  inf  4  5.0
1  3.0  2.0  3  4.0
2  NaN  4.0  8  2.0
3  4.0  3.0  5  NaN

In [ ]:
df["A"].isna()

0    False
1    False
2     True
3    False
Name: A, dtype: bool

In [ ]:
df["A"].dropna()

0    5.0
1    3.0
3    4.0
Name: A, dtype: float64

In [ ]:
df["A"].fillna('SEM DADOS')

0          5.0
1          3.0
2    SEM DADOS
3          4.0
Name: A, dtype: object

# **Pandas df.at | df.iat**

## df.at()
Acesse um único valor para um par de **`rótulos`** de linha/coluna.

Semelhante a loc, pois ambos fornecem pesquisas baseadas em **`rótulos`**. Use at se você precisar obter ou definir apenas um único valor em um DataFrame ou Series.

## df.iat()
Acesse um único valor para um par de linha/coluna por **`posição inteira`**.

Semelhante a iloc, pois ambos fornecem pesquisas baseadas em **`números inteiros`**. Use iat se você precisar obter ou definir apenas um único valor em um DataFrame ou Series.


In [ ]:
df = pd.DataFrame([[0, 2, 3], [0, 4, 1], [10, 20, 30]],
                  index=[4, 5, 6], columns=['A', 'B', 'C'])
df

A   B   C
4   0   2   3
5   0   4   1
6  10  20  30

In [ ]:
df.at[4, 'B']

2

In [ ]:
df.iat[0, 1]

2

# **Pandas loc | iloc**


## df.loc()

Acesse um grupo de linhas e colunas por rótulo(s) ou uma matriz booleana.

.loc é baseado principalmente em rótulos, mas também pode ser usado com uma matriz booleana

## df.iloc()

Indexação puramente baseada em localização inteira para seleção por posição.

.iloc é principalmente baseado em posição inteira (de 0 até length-1 do eixo), mas também pode ser usado com uma matriz booleana.


## **Observação**:
Existem inumeras aplicações para as funções loc e iloc, para mais informaçoes consultem:

[Documentação .loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc)

[Documentação .iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc)


In [ ]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
     index=['cobra', 'viper', 'sidewinder'],
     columns=['max_speed', 'shield'])
df

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [ ]:
df.loc['viper']

max_speed    4
shield       5
Name: viper, dtype: int64

In [ ]:
df.iloc[1]

max_speed    4
shield       5
Name: viper, dtype: int64

# **Pandas Concat**

## Descrição:
Concatenar objetos pandas ao longo de um eixo específico.

Permite definir lógica opcional ao longo dos outros eixos.

Também pode adicionar uma camada de indexação hierárquica no eixo de concatenação, o que pode ser útil se os rótulos forem iguais (ou sobrepostos) no número do eixo passado.



In [ ]:
import pandas as pd

In [ ]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

pd.concat([s1, s2])
#pd.concat([s1, s2], axis=1)
#pd.concat([s1, s2], ignore_index=True)
#pd.concat([s1, s2], keys=['s1', 's2'], names=['name1', 'name2'])


name1  name2
s1     0        a
       1        b
s2     0        c
       1        d
dtype: object

In [ ]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])

pd.concat([df1, df2])


letter  number
0      a       1
1      b       2
0      c       3
1      d       4

# **Pandas DataFrame Groupby**

## Descrição:
Agrupe DataFrame usando um mapeador ou por uma série de colunas.

Uma operação groupby envolve alguma combinação de dividir o objeto, aplicar uma função e combinar os resultados. Isso pode ser usado para agrupar grandes quantidades de dados e computar operações nesses grupos.

In [ ]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                    'Max Speed': [380., 370., 24., 26.]})

df

Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [ ]:
df.groupby(['Animal']).sum()

Max Speed
Animal           
Falcon      750.0
Parrot       50.0

# **Pandas DataFrame Filter**

## Descrição:
Subconjunto as linhas ou colunas do dataframe de acordo com os rótulos de índice especificados.

Observe que essa rotina não filtra um dataframe em seu conteúdo. O filtro é aplicado aos rótulos do índice.

In [ ]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['one', 'two', 'three'])
df

one  two  three
mouse     1    2      3
rabbit    4    5      6

In [ ]:
df.filter(items=['one', 'three'])

one  three
mouse     1      3
rabbit    4      6

In [ ]:
df.filter(regex='e$', axis=1)

one  three
mouse     1      3
rabbit    4      6

In [ ]:
df.filter(like='bbi', axis=0)

one  two  three
rabbit    4    5      6

# **Pandas DataFrame Query**

## Descrição:
Consulte as colunas de um DataFrame com uma expressão booleana.

Você pode fazer referência a variáveis ​​no ambiente prefixando-as com um caractere '@' como .@a + b

Você pode fazer referência a nomes de colunas que não são nomes de variáveis ​​Python válidos colocando-os entre acentos graves. Assim, nomes de colunas contendo espaços ou pontuações (além de sublinhados) ou começando com dígitos devem ser cercados por acentos graves. (Por exemplo, uma coluna chamada “Área (cm^2)” seria referenciada como ). Os nomes das colunas que são palavras-chave do Python (como “list”, “for”, “import”, etc) não podem ser usados. `Area (cm^2)`

Por exemplo, se uma de suas colunas for chamada e você quiser somar com , sua consulta deverá ser .a ab`a a` + b


In [ ]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(10, 0, -2),
                   'C C': range(10, 5, -1)})
df

A   B  C C
0  1  10   10
1  2   8    9
2  3   6    8
3  4   4    7
4  5   2    6

In [ ]:
df.query('A > B')

A  B  C C
4  5  2    6

In [ ]:
df.query('B == `C C`')

A   B  C C
0  1  10   10

# **Numpy Where**

## Descrição:
A função numpy.where() retorna os índices dos elementos em uma matriz de entrada onde a condição dada é satisfeita.

Sintaxe: numpy.where (condição [, x, y])
Parâmetros:
condição: Quando True, retorna x, caso contrário, retorna y.
x, y: valores para escolher. x, y e a condição precisam ser transmitidos para alguma forma.

Retorna:
out: [ndarray ou tupla de ndarrays] Se xey forem especificados, a matriz de saída contém elementos de x onde a condição é True e elementos de y em outro lugar.

Se apenas a condição for fornecida, retorne a tupla condição.nonzero(), os índices onde a condição é Verdadeira.

In [ ]:
import numpy as np

a = np.random.randn(2, 3)
print(a)

[[-1.45949906  1.07279406  0.92414444]
 [ 0.54339953 -0.19482648  0.71965488]]


In [ ]:
b = np.where(a > 0, a, 0)

print(b)

[[0.         1.07279406 0.92414444]
 [0.54339953 0.         0.71965488]]


In [ ]:
import numpy as np

a = np.arange(10)
b = np.where(a < 5, a, a * 10)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [ ]:
import numpy as np
import pandas as pd

my_array = np.array([[11,22,33],[44,55,66]])

df = pd.DataFrame(my_array, columns = ['Column_A','Column_B','Column_C'])

df

Column_A  Column_B  Column_C
0        11        22        33
1        44        55        66

In [ ]:
df.Column_A = np.where(df.Column_A < 20, 'Valor baixo', 'Valor Alto')

In [ ]:
df

Column_A  Column_B  Column_C
0  Valor baixo        22        33
1   Valor Alto        55        66

# **Filtros em DataFrames**

##Descrição:
Filtros em DataFrame como o proprio nome já diz, são formas na qual através de uma condição consulta\extrair dados em dataframes maiores.

In [ ]:
from pandas.io.formats.info import DataFrameTableBuilderNonVerbose
import pandas as pd

# assign data
df = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})


In [ ]:
df

Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [ ]:
df[df['Age'] > 30]

Name  Age  Salary          JOB
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT

In [ ]:
df[(df['Age'] > 30) &
   (df['Salary'] > 93000) &
   (df['JOB'] == 'IT')]

Name  Age  Salary JOB
4  CHANDLER   34   94000  IT

In [ ]:
df[(df['Age'] > 30) &
   (df['Salary'] > 93000) &
   (df['JOB'] == 'IT')].Age

4    34
Name: Age, dtype: int64

In [ ]:
df[(df['Age'] > 30) & (df['Salary'] == 94000)].Age[4] # '&' simbolo para condição 'and'

34

In [ ]:
df[(df['Age'] > 30) | (df['Salary'] == 94000)].Age[4]# '|' simbolo para condição 'or'

In [ ]:
df[(df['Age'] > 30) & (df['Salary'] == 94000)].Age.reset_index(drop=True)[0]

34

In [ ]:
df[df['JOB'].str.contains('(?i)(desi)', regex=True)]

<ipython-input-9-84ad1e49c755>:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  df[df['JOB'].str.contains('(?i)(desi)', regex=True)]


Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

In [ ]:
df[df['JOB'].str.match('(?i)(desi)')]

Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

# **Metodos aritimeticos e outros**

### **`pd.read_csv(usecols=lista_de_nome_colulas)`**
Carrega em memoria apenas as colunas do dataframe que foram espeficidas nesse parametro.

### **`pd.read_csv(nrows=numero_de_linhas)`**
Carrega em memoria apenas a quantidade de linhas do dataframe que foram espeficidas nesse parametro.

### **`df.info(memory_usage='deep')`**
Exibe a quatidade de memoria que um datafrma está utilizando.

### **`DataFrama.info()`**

print das informações sobre o data frame

### **`DataFrame.dtypes`**

exibe os tipos das colunas do dataframe

### **`DataFrame.column.value_counts()`**

contagem de valores dentro da coluna

### **`DataFrame.columns`**

extrai um data frame das colunas.

### **`DataFrame.column.unique()`**

extrai uma lista dos valores únicos da colunas

### **`DataFrame.sample(numero)`**

extrai uma amostra aleatória de linhas do data frame

### **`DataFrame.describe()`**

retorna informações de contagem, media, desvio padrão, mínimo e máximo e quartil.
